.PHONY: clean All

All:
	@echo "----------Building project:[ density_tests - Release ]----------"
	@"$(MAKE)" -f  "density_tests.mk"
clean:
	@echo "----------Cleaning project:[ density_tests - Release ]----------"
	@"$(MAKE)" -f  "density_tests.mk" clean
